name: getRanking

on:
  schedule:
    - cron: "0 20 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Run updateChart.py
        run: |
          python scripts/updateRanking.py
      - name: Commits
        run: |
          git config --local user.email "khr5k0228@gmail.com"
          git config --local user.name "hyeongrok7874"
          git add app/src/pages/api/ranking.json
          git commit -m "Auto update ranking.json"
      - name: Push
        run: |
          git push
